### ISSUE TITLE
All map outfitters panel shows all items for sale at 100% of outfitters

### ISSUE THREAD

**Issue by samrocketman** [Endless-Sky-Pirate-Campaign/endless-sky#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Playing from commit 70f2c2b1700ddc65cb1aa40bbd9333ccc1893f31 on `pirate-complete` branch.

Finding where outfits are for sale is not currently possible.

### Commit introducing bug

I ran `git bisect` and found this commit introduces the bug: https://github.com/Endless-Sky-Pirate-Campaign/endless-sky/commit/7f33de2caabebc345b3602cd41a27232bde9fd44

### Steps to Reproduce

1. Press M for map
2. Press O for Outfitters Map panel
3. Click on different outfits for sale to see which outfitter sells them
4. Notice 100% of all outfitters are reported as selling every outfit.  Even if an outfitter does not sell an item it will still be reported as such.

### Expected Behavior

Clicking on different outfitters should show the map having different

### Screenshots

Notice every outfitter is orange (only some should be orange).

![Screenshot from 2022-01-12 16-08-27](https://user-images.githubusercontent.com/875669/149221701-d15fa5c3-abda-458a-8104-69c084a300ae.png)

### Operating System

Ubuntu 20.04.3 LTS

### Game Source

Other (please describe)

### Game Version

70f2c2b1700ddc65cb1aa40bbd9333ccc1893f31

### Additional Information

Here's is how I build the game to play it https://gist.github.com/samrocketman/6068b09f46c24370c359b2bae438b7a4

**Comment by Hurleveur** [comment]
just fixed it on my branch! it was a remnant of when the price for outfits would be sent back as 0 when they weren't sold somewhere
I optimized the code a bit whilst I was at it

**Comment by samrocketman** [comment]
Fixed on `pirate-complete` branch at commit 1cc1a2679d6177452b1edfb71218ab69f2b3d6be
